M48
; DRILL file {KiCad (6.0.5)} date Mon Jun 13 20:59:27 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-13T20:59:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X9.76Y-3.6
X9.76Y-3.915
T2
X6.635Y-2.575
X6.635Y-5.215
X9.815Y-2.575
X9.815Y-5.215
T0
M30
